services:
  db:
    image: postgres:16
    container_name: task-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tasksdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    image: task-api:latest
    container_name: task-api
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/tasksdb
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: task-frontend
    restart: unless-stopped
    ports:
      - "5500:80"
    depends_on:
      - api

volumes:
  postgres_data:
